- name: Manjaro Development Environment
  connection: local
  hosts: localhost

  pre_tasks:
    - name: Update Pacman
      become: true
      pacman:
        update_cache: yes
        upgrade: yes

  tasks:
    - include: tasks/zsh.yml
